### PR TITLE
3DS payment changes

### PR DESCRIPTION
**Pull request by martonx**
Hi,

I added all of the new 3DS model changes. Besides these I had to remove all of the .Net45 dependencies, as I have no .Net 45 on my machine, and never will be :D
Oh, and I updated Nuget packages also.

As I see there is only one breaking change comparing to previous StartPaymentOperation. This is the ShippingAddress. All of the other new properties are just additions.

I didn't updated tests, not tested my new properties, classes, enums. I suggest to create a new branch on your side, and merge my changes into it. not directly into master.

I hope I was able to help you!
Lajos

### CODE REVIEW

**Comment by szelpe** [comment]
Why did you remove the support for the .NET 4.5 runtime?

**Comment by martonx** [comment]
> Why did you remove the support for the .NET 4.5 runtime?

I have .Net 4.7.2 and up on my machine. I didn't want to install so old Framework to my machine, so instead I removed it, to see at least building. .Net 4.5 runtime support will really miss to anybody? :D

**Comment by szelpe** [comment]
When you develop a library which is used by several applications you want to support a more broad set of frameworks, and it doesn't really matter what is currently installed on your computer.

**Comment by szelpe** [comment]
Thank you for your contribution, I've merged your changes with the following amends:

- Removed unrelated changes (e.g. framework and library version changes)
- GiftCardPurchase Count with upper case letter
- ShippingAddress is not a special BillingAddress so the inheritance is not correct

**Comment by martonx** [comment]
Thx, next time I'll be more careful, and not commit into unrelated changes.

**Comment by szelpe** [comment]
Thanks, your changes are now available in the latest NuGet package :)

**Pull request closed without merging**
